name: CI

on:
    pull_request:
        branches: ['*']
    pull_request_review:
        types: [submitted]

env:
    isPullRequest: ${{ github.event_name == 'pull_request' }}
    isAprovedReview: ${{ github.event_name == 'pull_request_review' && github.event.review.state == 'APPROVED' }}

jobs:
    IsPullRequest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              if: ${{ env.isPullRequest }}

            - name: IsPullRequest
              run: echo "É um Pull Request"
            
    IsAprovedReview:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              if: ${{ env.isPullRequest }}
            
            - name: IsAprovedReview
              run: echo "A Revisão foi aprovada "
